### PR TITLE
Replace custom css for form elements on apply with Tailwind

### LINKED ISSUE #3439: Replace custom css for form elements on apply with Tailwind
I noticed that Hypha custom CSS in `_form.scss` stacks on top of Tailwind form styling a bit in places.

I think we can simply remove a lot of the custom code and fall back on stock Tailwind. Maybe adjust colours etc. only.

### PR DESCRIPTION
**Pull request by theskumar**
Fixes: #3439

### CODE REVIEW

**Comment by frjo** [comment]
Nice work!

The old radio and checkbox styles have a blue border. That is in this PR replaced with a more standard grey and they are slightly smaller as well.

I do not have a preference for one over the other but I prefer not to change things to much, unless we have a good reason.

Skärmavbild 2023-07-05 kl  10 26 51
Skärmavbild 2023-07-05 kl  10 27 11

**Comment by theskumar** [comment]
It could be the missing accent color on the check box, let me take a stab at it. Definitely not intensional, i get your point.

**Comment by theskumar** [comment]
Updated in 4eff69c4d
Screenshot 2023-07-05 at 08 51 01@2x

**Review by frjo — APPROVED** [review]
Perfect!

**Pull request merged**
