### PR TITLE
Make password required to change account 2FA

### LINKED ISSUE #2644: Require password on account 2FA change
**Is your feature request related to a problem? Please describe.**

As a user, when I am logged into my account on a device that I trust and I would like to change my 2 factor authentication associated with my account. I will be required to enter my current correct account password in order to confirm the change of 2 factor authentication.

**Is your feature request related to an existing functionality? Please describe.**

Not existing functionality but existing section in the /account area

**Describe the solution you'd like**

A solution that includes the logged in users current correct account password on request of 2 factor authentication change would also include error pathways for users including:

* If a user enters their password incorrectly
* A user enters an invalid 2 factor authentication process (this may need to be agreed at an organisational level e.g. this organisation approves use of google authenticator app and Microsoft's authenticator app but not others etc.)
* If a user spends to long on the page session and 'times out'

**Describe alternatives you've considered**

N/A

**Additional context**

This was part of the recommendations given by the security audit team circa Aug 2021.

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff
- Applicants
- Reviewers
- Partners

**Ideal deadline**

Date when you'd like to see this accomplished and a reason, if appropriate.
End of Q1 2022

### PR DESCRIPTION
**Pull request by sandeepsajan0**
Fixes #2644 

Add description here.

### CODE REVIEW

**Review by sks444 — APPROVED** [review]
Looks good!

@frjo, this is good to go on test.

**Comment by frjo** [comment]
@sks444 On test now.

**Comment by frjo** [comment]
@sks444 After merging in the password on e-mail change PR this PR has conflict. Can you please take a look.

**Comment by sks444** [comment]
Have rebased and fixed the conflicts @frjo.

**Pull request merged**
