### PR TITLE
Link comments icon to submission -> communications tab

### PR DESCRIPTION
**Pull request by theskumar**
## Test Steps

 - Goto "All submissions" > "List view"
 - In the rows, the comments icon is clickable and takes you to the submissions communication page

### CODE REVIEW

**Review by wes-otf — APPROVED** [review]

**Review by frjo — APPROVED** [review]

**Comment by wes-otf** [comment]
This worked super well! My only question was if it would make sense to mirror this functionality in the table view with the comment icon there? Otherwise ready to go

**Comment by frjo** [comment]
I will merge this is since it’s a nice feature that works well.

If the old table view sticks around we can add it there as well in a separate PR. The summer plan is however to create a table style for the new list view.

**Comment by wes-otf** [comment]
works for me!

**Comment by theskumar** [comment]
I'll get the comments linked in the new table view for submissions. The current table view is little harder to update.

**Pull request merged**
