### PR TITLE
Added descriptions to group selections in Wagtail admin

### LINKED ISSUE #3541: Add a definition next to each user role in wagtail admin
### Description

Add a definition next to each user role in the WagTail admin 

image

### PR DESCRIPTION
**Pull request by wes-otf**
Fixes #3541.

This PR adds descriptive help text to the Wagtail admin edit/create user "Groups" prompt. This was done by creating custom Wagtail forms and overwriting the existing group field, along with adding another field to the [groups.py](https://github.com/HyphaApp/hypha/blob/enhancement/add-desc-to-user-roles/hypha/apply/users/groups.py#L40).

The [definitions](https://github.com/HyphaApp/hypha/issues/3541#issuecomment-1786722987) provided by @fourthletter were shortened just a bit for the sake of appearance. If anyone believes they got too truncated I'm fine with updating them.

## Screenshots
Screenshot 2023-10-31 at 5 07 29 PM

Screenshot 2023-10-31 at 5 07 15 PM

Cheers!

### CODE REVIEW

**Comment by wes-otf** [comment]
The CI gods did not favor me today. Couldn't get the test to fail locally but will continue work tomorrow.

**Comment by fourthletter** [comment]
@wes-otf - I forgot to add definitions for staff admin and community reviewer 

**Staff Admin** view and edit all submissions, submit reviews, send determinations, and set up applications. Can disable 2FA, archive submissions, and other components not accessible to other roles.

**Community Reviewer** is an applicant with access to other applications for the Request with community review (peer review) workflow.

**Comment by frjo** [comment]
@wes-otf Try running:

`pytest --ds=hypha.settings.test --store-durations`

and then commit the updated `.test_durations` file to the PR. This sometimes resolves these kind of issues.

**Comment by frjo** [comment]
Please also test this on top of the Django 4 and Wagtail 5 PRs. Or we just wait until they have been merged it.

**Comment by frjo** [comment]
> **Staff Admin** view and edit all submissions, submit reviews, send determinations, and set up applications. Can disable 2FA, archive submissions, and other components not accessible to other roles.

This is not correct. Most of these are reliant on permission settings in Wagtail. These are completely up to each organisation to set to whatever they like.

The only thing I know for sure are linked to "Staf admin" is "View message log".

Important also to point out that "Staff admin" always should be used together with "Staff".

**Comment by wes-otf** [comment]
@frjo So should abilities given by wagtail permissions should not be included in the description? Would this effect any of the [given descriptions](https://github.com/HyphaApp/hypha/issues/3541#issuecomment-1786722987)?

> These are completely up to each organisation to set to whatever they like.

With the addition of [translations in groups.py](https://github.com/HyphaApp/hypha/blob/enhancement/add-desc-to-user-roles/hypha/apply/users/groups.py#L1), wouldn't different orgs be able to customize what that description is?

**Comment by wes-otf** [comment]
Just tested with both the Wagtail 5 branch & Django 4 branches, both worked totally fine. Only thing I saw is that our edit/create user templates use the Wagtail shared template `field_as_li.html` a few times and Wagtail has said this will be [removed in a future release](https://docs.wagtail.org/en/stable/releases/5.1.html#shared-include-field-as-li-html-will-be-removed). I could swap these out proactively if that would be worthwhile.

Otherwise this should be all set once confirmation is given on those final group descriptions! Tests looked to be failing because of a migration that wasn't made so that is also included here.

**Comment by wes-otf** [comment]
The latest updates that are ready for review:

Screenshot 2023-11-02 at 11 02 33 AM

**Review by theskumar — APPROVED** [review]

**Comment by frjo** [comment]
@wes-otf We merge in some other things so there are a merge conflict here.

**Comment by frjo** [comment]
Would be good to implement this on the "/admin/groups/" view as well.

**Comment by wes-otf** [comment]
Roger that, adding that in now.

**Comment by wes-otf** [comment]
This should be all set! Here's what the new Wagtail admin group list looks like:

Screenshot 2023-11-29 at 3 16 24 PM

**Comment by wes-otf** [comment]
Alright I believe it's actually set now. It looks like the changes in #3664 were overriding the wagtail admin user creation view so I took a stab at making it more programmatic with less code duplication. Saving users still works with the consent checkbox enabled.

@frjo @theskumar let me know if you guys have any more thoughts otherwise it's ready for test

**Review by frjo — APPROVED** [review]

**Comment by frjo** [comment]
Needs a new rebase to solve merge conflicts.

After that we put on test just to confirm and then I think it is ready to go.

**Comment by wes-otf** [comment]
All set here

**Pull request merged**
