### PR TITLE
Project and submission links

### PR DESCRIPTION
**Pull request by bickelj**
Issue #4117
Issue #4129

## Test Steps

 - [ ] As staff
 - [ ] Visit the Projects page `apply/projects/all/`
 - [ ] Visit one of the projects e.g. Project 3 (associated with Submission 5).
 - [ ] Verify that the link to Project 3 shows the Submission ID in the URL, e.g. `apply/submissions/5/project/`
 - [ ] Verify that the Communications tab is actually a link to the Submissions#communications tab. Click it.
 - [ ] Verify that a Project tab/link shows up on the Submission page and that it leads back to the associated Project.
 - [ ] Verify that other links to the Project or Submission work, e.g. from Invoices.

### CODE REVIEW

**Comment by frjo** [comment]
I see two big changes in this PR. 

1. Making project URLs a part of submission URLs.
2. Merging project and submission communication tabs.

If we go with 1 I think we should update URLs  for invoices and reports as well. We should also remove the "project/[0-9]+" URLs.

If we go with 2 there is no need to specify "Submission communications". It would just be "Communications".

@wes-otf What does OTF think of these two changes

@bickelj Why is the URL change important for your clients? My experience is that users do not look in the address-bar. Many browsers even actively hides the full address and only show the domain to help users combat fake sites.

**Comment by wes-otf** [comment]
Thanks @bickelj for upstreaming this! A few notes from me:

- URLs
    - I really like the new format & from the convos I've had OTF would be on board with that too. I think we have a few power users that may notice/utilize it.
    - Agreed with @frjo that it makes sense to refactor invoice & report URLs to be the same as the regular project URL
    - The old URL format should redirect to the new one (ie. `/apply/projects/<PROJECT ID>/` -> `/apply/submissions/<SUBMISSION ID>/project/`)
- Projects table view
    -  I'm a fan of showing the corresponding submission in the table but it makes more sense to me to present it like the old table view did (ie. `<Submission Name> (#<ID>)` with a link to the submission as opposed to just showing the ID.
- Submission detail view
    - `Go To Project` tab formatting should be the same as the `View Message Log` in terms of hover states & text formatting.
    - Should the `Project` sidebar item be kept if we have a `Go To Project` tab? Could we show the project name in a tooltip on hover?
- Project detail view
    - If we have a `Go To Project` tab on the submission detail view it makes sense to me to have a `Go To Submission` tab on the project
    - I'm a fan of the combined comms tab but I couldn't get it to show up when running locally. Only `Details` & `Activity Feed` tabs showed.

This was after a brief look so feel free to let me know if I overlooked anything. Cheers!

**Comment by theskumar** [comment]
https://github.com/HyphaApp/hypha/pull/3944 attempts something similar to what's done here. Essentially allows you to reference the submission or it's project by the same id. 

So if this feature is going in then #3944 can be closed.

**Comment by frjo** [comment]
The PR https://github.com/HyphaApp/hypha/pull/3944 handles all the URLs (reports/invoices). I might also prefer that approach.

@bickelj Can you take a look at that PR and see how it would work out for you?

**Comment by bickelj** [comment]
@wes-otf @frjo @theskumar I think, as we discussed in the maintainers' meeting, that #3944 and the merging of communications into a single feed would satisfy what we are looking for here.

**Comment by bickelj** [comment]
Superseded by #3944 and related.

**Pull request closed without merging**
