### PR TITLE
Upgrade Wagtail to 4.2

### LINKED ISSUE #3018: Upgrade to Wagtail 4.x
Wagtail 4.x supports Django 3.2 according to https://docs.wagtail.org/en/stable/releases/upgrading.html#compatible-django-python-versions

Short term we want access to Global settings, see https://docs.wagtail.org/en/stable/releases/4.0.html#global-settings-models

See https://docs.wagtail.org/en/stable/releases/4.0.html#upgrade-considerations

### PR DESCRIPTION
**Pull request by theskumar**
Fixes #3018

- Update requirements - `wagtail` and `wagtail-cache`
- Update `BaseSetting` to `BaseSiteSettings`
- Fix Category StreamBlock at hypha/apply/categories/blocks.py
- Add migration changes
- Add `wagtail_reference_index_ignore = True` to models (See [this issue](https://github.com/wagtail/wagtail/issues/9731) on wagtail for more info)
- Use checkboxes when selecting reviewers for a Round and a Lab
- Update `ReadOnlyPanel` to use `render_html()` method instead of `render_as_object()`

**Screenshots**

Update to UIs
Screenshot 2022-11-14 at 08 46 32@2x

### CODE REVIEW

**Comment by theskumar** [comment]
I tested it locally and was not able to find another issue. @sandeepsajan0 @frjo would be possible for you to check if anything breaks on your local database?

**Comment by theskumar** [comment]
Found an issue on this page: 
Screenshot 2022-11-17 at 10 01 32@2x

Screenshot 2022-11-17 at 10 02 30@2x

**Comment by theskumar** [comment]
Update got an issue with the `ModelChooserBlock` used in the `CategoryQuestionBlock.` That's what I'm trying to resolve, now.

Screenshot 2022-11-18 at 11 15 26@2x

**Comment by frjo** [comment]
I get this notice on the commandline:

~~~~
/Users/frjo/Sites/hypha/venv/hypha/lib/python3.10/site-packages/django/db/models/base.py:326: RemovedInWagtail50Warning: StreamField must explicitly set use_json_field argument to True/False instead of None.
  value.contribute_to_class(cls, name)
~~~~

**Comment by frjo** [comment]
Tested just now and during migration I get:

`django.db.migrations.exceptions.InconsistentMigrationHistory: Migration funds.0087_applicationsettings is applied before its dependency wagtailcore.0078_referenceindex on database 'default'.`

**Comment by frjo** [comment]
Regarding the"count increase due to ReferenceIndex". Was there not a setting to disable that? From what I understod it is not a feature Hypha really needs/make use of?

**Comment by frjo** [comment]
Tried to deploy to otf-devlop but hit "django.db.migrations.exceptions.InconsistentMigrationHistory: Migration funds.0087_applicationsettings is applied before its dependency wagtailcore.0078_referenceindex on database 'default'."

**Comment by theskumar** [comment]
> Tried to deploy to otf-devlop but hit "django.db.migrations.exceptions.InconsistentMigrationHistory: Migration funds.0087_applicationsettings is applied before its dependency wagtailcore.0078_referenceindex on database 'default'."

Fixed this by added a new empty migration in the `hypha.core` app, instead of modifying the old one.

**Comment by theskumar** [comment]
@frjo All is good from my side. Fixed a decent amount of depreciation warnings, while also preventing reference index to be automatically generated for the models that doesn't need them.

**Comment by frjo** [comment]
Works well for me now! Excellent work. Will test it some more locally and then deploy to the OTF dev env.

**Comment by theskumar** [comment]
Sounds great! I've also rebased it with the `main` now!

**Comment by theskumar** [comment]
Rebased with `main`.

**Comment by theskumar** [comment]
@frjo Does the branch automatically get updated on the dev site? 

I've rebased this branch with `main` and also fixed the issues.

**Comment by theskumar** [comment]
Rebased with latest / updated migration conflicts

**Comment by frjo** [comment]
I need to update the OTF dev branch manually, will get that done today.

**Comment by frjo** [comment]
Updated the overridden wagtail admin user templates, got a 500 error trying to edit a user. Deployed to OTF dev site now.

**Comment by theskumar** [comment]
Review/checked https://github.com/HyphaApp/hypha/pull/3045/commits/97d6926e4e448f2be6a7b24dc6e0ccb5335e9e40 and works perfectly for me!

**Comment by frjo** [comment]
Noticed an issue for the Round edit form.

This is how it looks in current Hypha:

Skärmavbild 2023-02-28 kl  08 30 49

This is with Wagtail 4.x in this PR.

The forms are not listed and there are no edit buttons.

Skärmavbild 2023-02-28 kl  08 31 47

**Comment by theskumar** [comment]
Resolved conflict with `main` and also fixed issues with the Form display:

Screenshot 2023-03-09 at 14 14 48@2x

**Review by frjo — APPROVED** [review]

**Comment by frjo** [comment]
Deployed latest to test.

**Review by frjo — APPROVED** [review]

**Pull request merged**
