### PR TITLE
Remove fancybox modal for Contracting

### LINKED ISSUE #4124: Convert remaining fancybox uses to htmx/alpine
- [ ] batch_determination_form.html
- [ ] batch_determination_confirmation.html
- [ ] invoice_admin_detail.html
- [ ] project_admin_detail.html
- [ ] project_approval_detail.html
- [ ] project_detail.html
- [ ] report_form.html
- [ ] contracting_documents.html
- [ ] invoices.html
- [ ] report_frequency_config.html
- [ ] report_line.html
- [ ] supporting_documents.html

### PR DESCRIPTION
**Pull request by sandeepsajan0**
Fixes #4124

- [ ] Use htmx/alpine for Upload contract modal
- [ ] Use htmx/alpine for Upload and remove contracting documents modal
- [ ] Use htmx/alpine for submit contracting documents modal
- [ ]  Use htmx/alpine for approve contract modal

## Test Steps

 - [ ] …

### CODE REVIEW

**Review by frjo — APPROVED** [review]
Works nicely!

**Comment by frjo** [comment]
A merge conflict in `contracting_documents.html` with other PR on test makes me hold off on this for a bit.

**Comment by frjo** [comment]
@sandeepsajan0 I have merged in https://github.com/HyphaApp/hypha/pull/4136 now so this PR needs a rebase before we can put it on test.

**Comment by sandeepsajan0** [comment]
@frjo It is rebased and ready to put on test.

**Comment by wes-otf** [comment]
worked really well!

**Pull request merged**
