### PR TITLE
Exclude draft submissions from API calls

### LINKED ISSUE #2850: Remove draft submission from API calls
Draft submission should not appear in any lists anywhere in Hypha.

### PR DESCRIPTION
**Pull request by sandeepsajan0**
Fixes #2850 

Add description here.

### CODE REVIEW

**Comment by sks444** [comment]
@sandeepsajan0, we may also add it [here](https://github.com/HyphaApp/hypha/blob/d6e2bb21a39d1fa7566cb60fe19f372dabfa5f0f/hypha/apply/api/v1/utils.py#L101). So we don't get screening statuses on draft submissions. And maybe [here](https://github.com/HyphaApp/hypha/blob/d6e2bb21a39d1fa7566cb60fe19f372dabfa5f0f/hypha/apply/api/v1/utils.py#L110) and [here](https://github.com/HyphaApp/hypha/blob/d6e2bb21a39d1fa7566cb60fe19f372dabfa5f0f/hypha/apply/api/v1/utils.py#L106).

**Comment by sks444** [comment]
@sandeepsajan0, we may also add it [here](https://github.com/HyphaApp/hypha/blob/d6e2bb21a39d1fa7566cb60fe19f372dabfa5f0f/hypha/apply/api/v1/utils.py#L101). So we don't get screening statuses on draft submissions. And maybe [here](https://github.com/HyphaApp/hypha/blob/d6e2bb21a39d1fa7566cb60fe19f372dabfa5f0f/hypha/apply/api/v1/utils.py#L110) and [here](https://github.com/HyphaApp/hypha/blob/d6e2bb21a39d1fa7566cb60fe19f372dabfa5f0f/hypha/apply/api/v1/utils.py#L106).

**Comment by frjo** [comment]
I think a fund or round with a draft submission should count as "used" so no need to update them.

For screening statuses I'm unsure if it is needed. Draft never should have a screening since staff can not see them.

**Comment by sks444** [comment]
Agree @frjo.

**Pull request merged**
