### PR TITLE
Add determination feature in React app

### LINKED ISSUE #2068: On the react interface, add "Determination" and "Review" buttons
* Upon click
* If draft exists, load the draft, if no draft, create a draft
* Collapse the leftmost screening sidebarS
* Shift the proposal page left and replace status/notes with a determination/review form
* Autosave draft as things are inputted
* Have a X/Close icon in the top right of that pane
* Upon click of X/Close, resize/go back to all default view

### PR DESCRIPTION
**Pull request by sks444**
Fixes https://github.com/OpenTechFund/hypha/issues/2068

### CODE REVIEW

**Comment by sks444** [comment]
@frjo, this adds the Add determination feature in react app. We may deploy it to test for testing purposes.

**Comment by Parbhat** [comment]
@frjo We can also deploy add determination feature to test environment.

**Comment by frjo** [comment]
Deploying to test now.

**Comment by Parbhat** [comment]
Noticed a few bugs. We will be fixing those soon.

**Comment by Parbhat** [comment]
Ready for testing. Imp note https://github.com/OpenTechFund/hypha/issues/2068#issuecomment-725362030

**Comment by frjo** [comment]
I have just now deployed the changes to test.

**Comment by sks444** [comment]
@frjo, that was only backend changes, can you redeploy the changes now? Thanks!

**Comment by frjo** [comment]
Done.

**Comment by frjo** [comment]
@sks444 Do you feel this is ready to deploy or better to hold off for now?

**Comment by sks444** [comment]
@frjo, let's hold off for now, this is a big change so will also do a code review once. Btw has this been tested internally by other team members?

Maybe we can deploy it next week.

**Comment by Parbhat** [comment]
@frjo This is ready to final review and deployment.

**Review by frjo — APPROVED** [review]
Will deploy first thing next week.

**Pull request merged**
