### PR TITLE
Update to Wagtail 2.16.1.

### LINKED ISSUE #2765: Update to Wagtail 2.16.1

### PR DESCRIPTION
**Pull request by frjo**
Fixes #2765

### CODE REVIEW

**Comment by frjo** [comment]
@sandeepsajan0 Can you help me figure out why the testa fail?

**Comment by sandeepsajan0** [comment]
@frjo Tests are failing because we are expecting class name as`<td class="field-<fieldname>">` in tests but with updated wagtail version we are getting class name as `<td class="field-<fieldname> title"`. There is an extra 'title' there. I am looking from where and why we are getting this 'title' in the class name. 

**Edited/Updated**
They have added a [TitleColumn class for the table columns with the link](https://github.com/wagtail/wagtail/commit/975c85f117655c6f3ca6dbce84981bdea4fa5a44). That's why we are having an extra 'title' class with the field class in tables.

**Comment by sandeepsajan0** [comment]
I tried with updated tests in my local and it works fine. Let me know, If updates in tests are okay to you I'll push the changes here.

**Comment by frjo** [comment]
@sandeepsajan0 Excellent find, please push.

**Pull request merged**
