### PR TITLE
Update modals to use htmx/alpine

### LINKED ISSUE #3391: Convert all dialogs/modals to use the <dialog> tag and htmx instead of fancybox lib
Hypha mainly use the fancybox lib for dialogs and modals. It works well. The dialog-tag nowadays have good support in all modern browsers.

The dialog-tag will:

* Simplify the code.
* Improve accessibility.
* One less thing that relies on jQuery.

Good articles on the subject:

* http://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
* https://blog.webdevsimplified.com/2023-04/html-dialog/

### PR DESCRIPTION
**Pull request by theskumar**
- Delete modal
- Update status modal
- update reviewer
- Archive/unarchive modal and view/logic
- Create reminder modal
- update reminder block design
- Add modal title component
- Django messages as toast for htmx request
- [x] update lead modal response
- [x] meta term modal
- [x] new project modal
- [x] partner update modal
- Adds new htmx based handler for django-message-framework and display them as toast

Fixes #3391

## Test Steps

 - [ ] Check above update modals work properly

### CODE REVIEW

**Review by frjo — CHANGES_REQUESTED** [review]
Really nice overall!

I do not think the modals should close when clicking the background, omnly when a button is pressed.

If you e.g. open the Reviewers modal pick some reviewers and then click outside the modal you loose your selection.

**Comment by theskumar** [comment]
> I do not think the modals should close when clicking the background, omnly when a button is pressed.

Yes. that can be made possible. 

Edit: fixed in https://github.com/HyphaApp/hypha/pull/4053/commits/850a50ea6fbeeaba7a2bd178518d02cb1e087356

**Comment by theskumar** [comment]
This is good to review now. I've updated/fixed the meta terms display and forms. It should correctly fill the values in edit now. 

Screenshot 2024-07-22 at 8  01 31@2x

**Comment by theskumar** [comment]
I'll fix over the failing test, the modal for the batch actions are not update, at the table view will be replaced soon in my next PR.

**Review by frjo — APPROVED** [review]

**Comment by frjo** [comment]
@theskumar Some minor issues with test. Seem to be looking for class names so might be an easy fix.

**Comment by theskumar** [comment]
@frjo Updated test cases.

**Comment by theskumar** [comment]
rebased with latest main.

**Comment by frjo** [comment]
Performance improvements:

1. Fewer db queries, 30-40% less.
2. Lower CPU time: 20-30% improvement.
3. Page load time: 10-15 % improvement.

**Review by wes-otf — APPROVED** [review]

**Comment by wes-otf** [comment]
This is fantastic! Testing went really well and everything looks much more slick. The only very minor issue I saw was the reminder toast showed twice upon creation but looking at the code that may be a reminders specific issue. 
Screenshot 2024-08-08 at 10 46 29

@frjo if it's determined that requires a separate issue this is ready to be merged

**Comment by theskumar** [comment]
> This is fantastic! Testing went really well and everything looks much more slick. The only very minor issue I saw was the reminder toast showed twice upon creation but looking at the code that may be a reminders specific issue.

This is probably because it's specifically being asked to display and other one is via the django messages framework through the activity feed route. I think it should be quick and safe to remove one of them.

**Comment by frjo** [comment]
Added new issue for reminder alter bug. https://github.com/HyphaApp/hypha/issues/4082

**Pull request merged**
