### PR TITLE
Rename Project Approval Form to Project Form

### LINKED ISSUE #3840: Rename PAF, "Project approval form" to something more generic
Maybe to the generic the "Project form"?

This will make it more clear the form can be used for whatever is needed.

### PR DESCRIPTION
**Pull request by sandeepsajan0**
Fixes #3840 

## Test Steps

 - [ ] Check for Project Approval Form text, it shouldn't be there in UI.

### CODE REVIEW

**Comment by frjo** [comment]
Did a rebase.

**Comment by wes-otf** [comment]
menus look good but wagtail still reads "Project approval forms" (and url is `/admin/application_projects/projectapprovalform/`, not sure if we want that updated or not): 
Screenshot 2024-04-30 at 16 10 48

**Comment by frjo** [comment]
@sandeepsajan0 Nice work! Issue with the migrations I think.

**Comment by sandeepsajan0** [comment]
@frjo I have resolved the migrations conflicts.

**Comment by wes-otf** [comment]
all looks good!

**Pull request merged**
