### PR TITLE
Fixes to application previews and draft refactoring

### LINKED ISSUE #3788: When editing an existing submission the save/submit button say "Preview and submit"
Staff can not save when editing an existing submission. The button say "Preview and submit" but you are never given the option to submit.

Applicants can save but the submission does not seem to progress when it should.

### PR DESCRIPTION
**Pull request by wes-otf**
## Description

Fixes #3788 and a few other issues. The main problems being seen around the preview were when it came to the edit view. This was because the use of the `Draft` status was being relied on for the saving of content before previews, when realistically a new application revision had the same effect. 

Previously, Admins/Staff could submit new applications, but could not submit existing applications. This is why when an Admin had attempted to submit a preview or submit an edited application, they could not do so. This functionality has been moved from `ApplicantSubmissionEditView` to `BaseSubmissionEditView` as it made sense to me that Admins would be able to access the same edit workflow & transitions as Applicants. I believe most OTF staff avoid editing incoming applications though.

## Test Steps

**Testing preview on initial apply**
 - [ ] As an Applicant, select `Apply` on any fund in the list on homepage
 - [ ] Populate some fields (ideally the ones that allow for text formatting)
 - [ ] Select the `Preview and submit` button
 - [ ] Confirm a preview with the application's rendered fields now appears, with `Submit` and `Edit` buttons at the bottom.
 - [ ] Confirm selecting `Submit` successfully submits the submission

**Testing preview on edit**
 - [ ] As an Applicant, select `Apply` on any fund in the list on homepage
 - [ ] Populate some fields (ideally the ones that allow for text formatting)
 - [ ] Select the `Save Draft` button at the bottom of the page
 - [ ] When redirected to the page stating`Your application is saved as a draft.`, select the `Continue editing` button.
 - [ ] Make changes to the application
 - [ ] Select the `Preview and submit` button
 - [ ] Confirm a preview with the updated application's rendered fields now appears, with `Submit` and `Edit` buttons at the bottom.
 - [ ] Confirm selecting `Submit` successfully submits the submission

**Testing revisions do not appear in revision list**
 - [ ] As an Applicant, select `Apply` on any fund in the list on homepage
 - [ ] Populate some fields (ideally the ones that allow for text formatting)
 - [ ] Select the `Preview and submit` button
 - [ ] In the preview, select `Edit` and edit some fields
 - [ ] Submit the application
 - [ ] As a staff member, navigate to the submitted application
 - [ ] Navigate to the revisions list
 - [ ] Ensure that there are no comparable revisions

### CODE REVIEW

**Comment by wes-otf** [comment]
Couldn't clamp the failing test locally but admittedly not totally familiar w/ Django's test factories. Will keep going tomorrow

**Comment by wes-otf** [comment]
This has opened a can of worms on how we handle application drafting/revisioning and some of the refactors that are needed there. Will revert back this PR to a draft for now but should have everything all said & done by the end of the week.

**Comment by theskumar** [comment]
Tested locally, and looking good so far.

**Comment by wes-otf** [comment]
Alright, I think this is finally all set. Took a bit of a tangent here to also fix some issues I saw with the drafting process, here's a summary of what this PR changes:
- [x] Added attribute of `is_draft` to revisions to also be able to differentiate what revisions are drafts.
    - Currently, if you create a new application but save it as a draft rather than submit, it will show up in revisions. This gets fixed here.
- [x] Updated revision list to not include revisions that have `is_draft` attributes unless that's the only revision available (such would be the case when `SUBMISSIONS_DRAFT_ACCESS_STAFF=True`)
- [x] Changed previews to leverage the `is_draft` state on revisions
- [x] Don't force staff to preview applications when editing them, but give them the option to do such
- [x] Removed `ApplicationSubmission` internal property `_is_draft` as it seems to have lost purpose from it's initial implementation 6 years ago
- [x] Added docstrings wherever possible

I added some `TODO` comments that I'll probably address as my next task. @theskumar made some good suggestions about how overloaded some of our models are with business logic so extracting out some of that would save some headaches down the road.

**Review by frjo — APPROVED** [review]

**Comment by wes-otf** [comment]
@frjo also going to hand this to the test team as I'd like to hear their input

**Comment by wes-otf** [comment]
Passed user testing 🎉

**Comment by frjo** [comment]
@wes-otf There is an issue with file uploads. If you try to upload a file to when you first apply it is lost.

Edit the submission later and add a file and it works.

**Comment by frjo** [comment]
@wes-otf Moving ` form.delete_temporary_files()` below the preview step seems to have done the trick. Files are saved in the proper way when I test now. Nice work!

**Comment by wes-otf** [comment]
yeah! it seems like that in tandem with the addition of 
```
{% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
{% endfor %}
```
in `application_preview.html` was what did it. The only issue I see now if that if you upload a file -> preview application -> edit -> preview, the file gets duplicated for some reason? Not sure if it's a residual of not deleting the temp files. Investigating today but hoping to get a better grip on what that temp file deletion does.

**Comment by frjo** [comment]
@wes-otf I think that is an old issue we have, see https://github.com/HyphaApp/hypha/issues/3237

**Comment by wes-otf** [comment]
Oh great! Then I think this is all set and I can take a look at #3237 after

**Review by sandeepsajan0 — APPROVED** [review]

**Comment by wes-otf** [comment]
@frjo how are you feeling on this? hoping to avoid merge conflicts

**Comment by frjo** [comment]
@wes-otf  I think this is good to go.

**Pull request merged**
