### PR TITLE
Make background color consistent across the app

### PR DESCRIPTION
**Pull request by wes-otf**
The applicant dashboard (and various other views) used tailwind's `bg-light-grey` which seems inconsistent with the overall app and caused the menu to have a different standout color.

Screenshot 2024-07-17 at 11 39 32

I believe the grey background does add a nice contrast to things so I made that the system default. Open to making it all white, though.

## Test steps
- [ ] Ensure there are no inconsistencies with background color & menu/tab items

### CODE REVIEW

**Comment by frjo** [comment]
Nice to get consistent colours!

I think the default should be white.

The light grey do look nice when there is big boxes like on the Dashboard.

**Comment by wes-otf** [comment]
That sounds good. Should I put the `block body_class` tags (with `bg-light-grey`) back in but for all the dashboards or just leave it all white?

**Comment by frjo** [comment]
Maybe make all white first and then we can consider?

**Comment by wes-otf** [comment]
I totally forgot about this for a bit but white is now the default background, let me know if you like this more or if we should switch back to grey @frjo

**Review by frjo — APPROVED** [review]

**Comment by frjo** [comment]
@wes-otf Needs a rebase after the the latest additions to main.

**Review by frjo — APPROVED** [review]

**Pull request merged**
