### PR TITLE
Provide project overview page access to Finance and Contracting team

### LINKED ISSUE #3454: Give finance and contracting roles access to Project overview

### PR DESCRIPTION
**Pull request by sandeepsajan0**
Fixes #3454

@frjo I have hidden the 'Invoices' and 'Reports' tables from the project overview page for the Contracting team. Finance and Staff have access to all tables.
I have updated project access(project detail page) permissions as well for the Contracting and Finance team. Currently, Contracting can access project only in 'Internal Approval and Contracting' state while Finance can access it in 'Internal Approval and Invoicing' state but with this PR changes, both of the user groups have access to all projects in all statuses but yes their actions are still limited, they can only view the project.

### CODE REVIEW

**Comment by frjo** [comment]
@sandeepsajan0 Needs a rebase, thanks!

**Comment by sandeepsajan0** [comment]
@frjo I have rebased it with project status update PR.

**Comment by sandeepsajan0** [comment]
@frjo This one is also ready for testing.

**Comment by fourthletter** [comment]
Thank you for pushing this through!

**Pull request merged**
