### PR TITLE
Cleanup code related to payment requests

### LINKED ISSUE #2579: Clean out paymentrequest code in favour of invoice
There are models/views/templates etc for paymentrequest. They should all be removed. If parts of the code still is relevant rename all funktions etc. to "invoice*".

- [ ] On the project overview page "/apply/projects/" there is a table "Payment Requests". Rename to "Invoices and list invoices with links to invoice views."
- [ ] On the staff dashboard there is a table "Active requests for payment". Rename ot "Project invoices" and rebuild "active_payment_requests" funktion to list invoices.

### PR DESCRIPTION
**Pull request by chaitu210**
Fixes #2579

Removed code related to payment requests.
Fixed testcases.

### CODE REVIEW

**Comment by frjo** [comment]
@chaitu210 Hi, please rebase this of latest main, I have merged in the Deliverables PR now.

**Review by sks444 — APPROVED** [review]
Looks Good. Nice Work @chaitu210!

@frjo can we deploy this to test?

**Comment by frjo** [comment]
Deployed to test now.

**Comment by frjo** [comment]
A number of projects on test, e.g. https://test-apply.hypha.app/apply/projects/25/, returns a Internal Server Error (500) with this PR. Other works well, like https://test-apply.hypha.app/apply/projects/6/

**Comment by sks444** [comment]
@frjo this can be redeployed to test.

**Pull request merged**
