### PR TITLE
Add Organization Name Column

### LINKED ISSUE #3290: Add organization name column to submissions table
**Is your feature request related to a problem? Please describe.**

The client normally looks at submissions by organization name, and not submitter name.  They refer to things as the "X Institute" submission, etc.  But that information isn't easily accessible on the table.

**Is your feature request related to an existing functionality? Please describe.**

This affects all the tables that list submissions

**Additional context**

This requires that the organization name become a top level field on the Submission model

**Priority**

- Medium (slowing you down)

This was a medium priority item for our client, but we solved it in our fork and a PR will be forthcoming

### PR DESCRIPTION
**Pull request by frankduncan**
Fixes #3290

Adds an organization name column to the submission table.  To effect that change, a new unique block needed to be added.  I did test that the column will not show up when added to `SUBSMISSION_TABLE_EXCLUDED_FIELDS`

### CODE REVIEW

**Review by frjo — CHANGES_REQUESTED** [review]
Looks good but have missing migrations and need a rebase to make sure the migrations are up to date.

**Comment by frankduncan** [comment]
I don't think this needs a migration.  At least, it works for me without one (and there's none on our original changes).  `python manage.py makemigrations` detected no changes

**Comment by frjo** [comment]
@frankduncan Hypha CI and my local environment both claims migration is needed. Se failed tests below.

**Comment by frankduncan** [comment]
Migration added, though interesting that it didn't seem to be required for the feature to work for me.  Hopefully the CI will be happy with the changes :)

**Review by frjo — APPROVED** [review]

**Pull request merged**
