### PR TITLE
Added filter to convert decimal review score to whole number.

### LINKED ISSUE #3343: Display individual review score as whole number.
**Is your feature request related to an existing functionality? Please describe.**

Display individual review score as whole numbers.

**Priority**

- Low priority

**Affected roles**

- Staff
- Admin

### PR DESCRIPTION
**Pull request by gmurtaza00**
Added filter to convert decimal review score to whole numbers.

image

image

image

Closes #3343

### CODE REVIEW

**Review by frjo — CHANGES_REQUESTED** [review]
This seems very subjective what you prefer. I do ot think we will hardcode a change. Making it adjustable with a setting with a defult the same as today would be good I think.

**Comment by gmurtaza00** [comment]
> This seems very subjective what you prefer. I do ot think we will hardcode a change. Making it adjustable with a setting with a defult the same as today would be good I think.

We can make a setting for this but the values specified in options.py file for reviews are in whole numbers. So I guess it better that we display them as whole numbers not decimals.

image

**Comment by frjo** [comment]
Yes, each review question can only be a whole number. A review will in many cases have several so the average will seldom be a whole number.

**Comment by gmurtaza00** [comment]
> Yes, each review question can only be a whole number. A review will in many cases have several so the average will seldom be a whole number.

Got your point. Actually we customized if for ARDC to just calculate sum and not average and it was the follow up issue for that.

**Pull request closed without merging**
