### PR TITLE
Fix submission search input

### LINKED ISSUE #3957: Search field on list view do not clear old search term
Going to https://test-apply.hypha.app/apply/submissions/all-alt/ and search for "first". Then search for "second".

The resulting URL becomes `https://test-apply.hypha.app/apply/submissions/all-alt/?query=first&query=second`

Notice that you now have two search parameters in the URL. Only the last parameter should be present.

### PR DESCRIPTION
**Pull request by theskumar**
Fixes #3957

Fixes the query parameter being show twice while searching twice on the
page.

The issues was that both `<form>` and `hx-include` was adding data when the
form was submitted with "Enter" key.

## Test Steps

 - Go to the submission all page
 - Search for a submission
 - Then search for another submission

### CODE REVIEW

**Review by frjo — APPROVED** [review]
Works mostly well but I'm not sure about auto run searches. It glitches sometimes if you type slowly and part of your search term are lost. I would lean towards using old and established enter to initiate search.

I also get a number of js errors (click draft and archive toggels):

~~~~
[Error] The selector "input.js-filter-options:not([name=archived])" on hx-include returned no matches!
	w (htmx.min.js:1800)
	Se (htmx.min.js:619)
	cn (htmx.min.js:2188)
	he (htmx.min.js:2804)
	(anonym funktion) (htmx.min.js:1550)
	i (htmx.min.js:1474)
[Error] htmx:historyCacheError
	w (htmx.min.js:1800)
	de (htmx.min.js:1816)
	fe (htmx.min.js:1782)
	Vt (htmx.min.js:1875)
	zt (htmx.min.js:1921)
	Mn (htmx.min.js:3156)
	(anonym funktion) (htmx.min.js:2909)
[Error] The selector "input.js-filter-options:not([name=drafts])" on hx-include returned no matches!
	w (htmx.min.js:1800)
	Se (htmx.min.js:619)
	cn (htmx.min.js:2188)
	he (htmx.min.js:2804)
	(anonym funktion) (htmx.min.js:1550)
	i (htmx.min.js:1474)
[Error] htmx:historyCacheError
	w (htmx.min.js:1800)
	de (htmx.min.js:1816)
	fe (htmx.min.js:1782)
	Vt (htmx.min.js:1875)
	zt (htmx.min.js:1921)
	Mn (htmx.min.js:3156)
	(anonym funktion) (htmx.min.js:2909)
~~~~

**Review by frjo — COMMENTED** [review]
See comment above.

**Comment by theskumar** [comment]
Thanks @frjo for the review. I'll remove the auto search and look into the console log issue

**Comment by theskumar** [comment]
Updated. 

For the js console error log, i've fixed it using a hack but I'll watch this issue and later fix it as recommended. https://github.com/bigskysoftware/htmx/issues/2556

**Comment by frjo** [comment]
In this version the enter key doesn not seem to activate search. Adding `hx-trigger="keyup[key=='Enter'], search"` fixes it.

Is there a way to get the search to clear/reset when clicking the "x" in the search input files. Now it clears the text input (browser feature I believe) but do not reset the search result.

**Comment by theskumar** [comment]
> Is there a way to get the search to clear/reset when clicking the "x" in the search input files. Now it clears the text input (browser feature I believe) but do not reset the search result.

This seems to a bug with safari. It works on chrome were I was testing it. Let me look into the alternative solutions

**Comment by theskumar** [comment]
Pushed another round of updates. The `input=search` behavior varies across different browsers[1], so I removed it entirely.

Instead, a proper "clear" action is now displayed below. This was previously shown when filtering from the dropdown, but now it will also appear when you search.

[1] Safari doesn't trigger onsearch when the clear button is clicked, while Chrome does.

**Review by frjo — APPROVED** [review]
Works perfectly for me now.

**Pull request merged**
