### PR TITLE
Add a separate DRAFT_SUBMISSION event

### LINKED ISSUE #3021: Remove slack alerts and notifications for DRAFT submissions

### PR DESCRIPTION
**Pull request by sandeepsajan0**
Fixes #3021 

NEW_SUBMISSION is getting used to notify staff members on slack and also to notify the applicant. But for draft submission, only the applicant should get the notification, there shouldn't be any recorder activity or slack notification. 
So, added a separate event DRAFT_SUBMISSION that only sends the notification/email to the applicant.

### CODE REVIEW

**Comment by fourthletter** [comment]
I still see slack alerts for drafts 

image

**Comment by fourthletter** [comment]
This patch was released last December 2022 but I still receive an alert on the live site

**Comment by frjo** [comment]
Yes, it is not deployed on live yet, only on test.

**Comment by fourthletter** [comment]
Thank you. I created a draft on test and it didn't send a notification. It works great!

**Pull request merged**
