### PR TITLE
Fix errors for compare revisions page(JSONDecodeError and Invalid literal int error)

### LINKED ISSUE #3709: Editing a submission leads to duplicate entries in the "revisions" section, one of which causes an error
When a proposal has been edited, it will sometimes create a duplicate entry in the revisions section. One of these duplicates (typically the oldest entry) will result in an error of `invalid literal for int() with base 10: ''` at [hypha/apply/funds/blocks.py](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/funds/blocks.py#L200) when attempting to open it, due to a lack of a `duration` field.

### PR DESCRIPTION
**Pull request by sandeepsajan0**
Fixes #3709

### CODE REVIEW

**Review by frjo — APPROVED** [review]

**Comment by frjo** [comment]
@wes-otf Can you please test this since you have a good grasp of the issue.

**Comment by wes-otf** [comment]
@frjo totally! is it on test yet? I think that's going to be the easiest way to confirm all is amended

**Comment by frjo** [comment]
Deploying to test now, will take a couple of minuts.

**Comment by wes-otf** [comment]
looks like it works to me!

**Review by wes-otf — APPROVED** [review]

**Pull request merged**
