### PR TITLE
Improvements in Project UI

### LINKED ISSUE #3311: "Approvals" section on the PAF is always empty
It should show a list of users that have approved the PAF.

### LINKED ISSUE #3318: Update text in popup when the contractor is uploading the contract
### Description

Need to update the pop up when the contractor is uploading the contract. We need to make sure that the contractor is aware that the contract will be sent to applicant once submitted.

### LINKED ISSUE #3321: Next step says PAF and the table says Approval form
Next step says PAF and the table says Approval form. We should have consistent terminology. [Figma update](https://www.figma.com/file/cmrfUklaIibgEYRFUIifuE/Hypha-designs?node-id=241-2603&t=YvHN9jxgiyBaNJju-4).

image

### LINKED ISSUE #3322: Update the language in the next step box. Change to “Submit for approval”
Update the language in the next step box. Change to “Submit for approval”. [Figma update](https://www.figma.com/file/cmrfUklaIibgEYRFUIifuE/Hypha-designs?node-id=243-2819&t=YvHN9jxgiyBaNJju-4).

image

### LINKED ISSUE #3323: Change the button to ‘Resubmit’ when someone requests for change and the PM is trying to submit the PAF after editing
Change the button to ‘Resubmit’ when someone requests for change and the PM is trying to submit the PAF after editing.

image

### LINKED ISSUE #3324: Revise step to say “Review the contract for all relevant details and approve”
### Description 

User didn’t know what ‘Approve contract’ meant. The next step should say “Review the contract for all relevant details and approve”. [Figma update](https://www.figma.com/file/cmrfUklaIibgEYRFUIifuE?node-id=432:9757#408228815)

image

### PR DESCRIPTION
**Pull request by sandeepsajan0**
- Add contract upload/updated_at date
- Break applicant instructions
- Fix css buttons issues
- Show the category above the document name
- Add back to project link in PAF edit page
- Make headers collapsible based on project status
- Unhide contract download option after contracting status
- Hide PAF Approvals for the applicant
- Hide Add invoice except for staff and applicant
- Add 'Upload invoices' as the next step for project with IN PROGRESS status.
- Add icons to all the project page's action buttons (except document actions).
- Add notification bar for project actions. #3326 
- Greyed Pending PAF approvals(below next step section)
- Fix #3318 
- Fix #3321 
- Fix #3322 
- Fix #3324
- Fix #3323
- Fix #3311

### CODE REVIEW

**Comment by sandeepsajan0** [comment]
@frjo I think we can put it on the test, it may make our testing smoother. The buttons' iconography still needs some work but this PR contains changes for the things mentioned above in the PR description.

**Comment by frjo** [comment]
Deploying the latest version of this PR to test now.

**Comment by sandeepsajan0** [comment]
@frjo Should I create a separate PR for upcoming changes?

**Comment by frjo** [comment]
@sandeepsajan0 Do what is easiest for you. If you want I can merge this in to main directly?

**Comment by sandeepsajan0** [comment]
This PR contains mostly Ui and text-related changes, so I think it is better to merge it in. I'll create a separate PR for the other changes.

**Pull request merged**
