### PR TITLE
Add dir attribute to the html tag, ltr/rtl.

### LINKED ISSUE #3726: Improve RTL support
- [x] Add configurable dir attribute to base templates.

### PR DESCRIPTION
**Pull request by frjo**
Fixes #3726

### CODE REVIEW

**Comment by frjo** [comment]
@frankduncan This add basic rtl support to Hypha. Django can autodetect the direction so no settings needed, if you e.g. set the language to "ar" the direction will be "rtl" as it should be.

**Comment by frjo** [comment]
Hypha has a sass function "opposite-direction" to handle ltr/rtl but that is an old way of doing it. You must also explicitly make use of it everywhere and that is not so now.

Much better is to replace all use of things like "margin-right" with "margin-inline-end", "padding-top" with "padding-block-start" etc. With these you get rtl support without doing anything, the browser just does the right thing.

**Review by theskumar — APPROVED** [review]
Nice 💯

**Comment by frankduncan** [comment]
Ah!  This will be great when hypha as a whole is set to an RTL language (and the localization file is created with all the translations).  We'll still need a solution when it has to do both simultaneously.  Something like #3293 would help with that.

**Pull request merged**
