### PR TITLE
Enchancement to pdf rendering

### LINKED ISSUE #3653: Upgrade xhtml2pdf to 0.2.13 and reportlab (or rebuild PDF generation with other tools)
Current version: 0.2.11

xhtml2pdf 0.2.12 depends on the reportlab>4 ([release notes](https://xhtml2pdf.readthedocs.io/en/latest/release-notes.html#id2)), while reportlab==3.6.13 is an explicit dependency on this project. 

Make sure the reportlab requirement doesn't break the code for the `make_pdf` code in  `hypha/apply/utils`

### PR DESCRIPTION
**Pull request by theskumar**
Fixes #3653 

- Refractor to use base-pdf.html
-  Fix html tags rendering in pdf
- Refractor pdf rendering logic of PAF
- Convert PDFSetting to be a generic setting
- Upgrade xhtmltopdf to latest

### CODE REVIEW

**Comment by theskumar** [comment]
@frjo The tests are passing now, had a small typo in the last commit.

**Review by frjo — CHANGES_REQUESTED** [review]
Looks good! Can we remove the xhtml2pdf update from this PR. I have created https://github.com/HyphaApp/hypha/pull/4251 that updates all the packages, including xhtml2pdf.

**Comment by theskumar** [comment]
Updated.

**Review by frjo — APPROVED** [review]

**Comment by wes-otf** [comment]
This is a massive improvement! This would've been a problem for OTF so thanks for getting in front of it @theskumar!

**Comment by wes-otf** [comment]
in testing this I did find #4259 which I could take a look at

**Pull request merged**
