### PR TITLE
Add status update batch action to invoices table

### PR DESCRIPTION
**Pull request by sandeepsajan0**
## Description

Fixes part of #3537

image

## Test Steps

 - [ ] Invoices table should be accessible to staff and finance
 - [ ] Staff and Finance both should have the option to select the invoices and update their statuses(depending on their statuses)
 - [ ] Check the statuses order like finance shouldn't be able to `paid` an invoice that is not `Approved by finance` yet.
 - [ ] Play around and provide your feedback.

### CODE REVIEW

**Comment by wes-otf** [comment]
In testing when there were two invoices that had the status `Paid`, selecting both of these and attempting updating the status to `Payment failed` results in a 500 with:

```
sequence item 0: expected str instance, NoneType found
```

At [activity_feed.py](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/activity/adapters/activity_feed.py#L170). More info in sentry but it still seems to update the status. Seemed also specific to these statuses as others would update w/o issue. This was done as the finance role.

**Comment by sandeepsajan0** [comment]
@frjo Its latest version is ready to put on test. 
@wes-otf There were issues with older invoices because we added invoice_number recently to the invoice model and as nobody was using the project/invoices so we didn't handle it for the older ones and let it None.
image

Although this was working fine for invoices with invoice_number so it wouldn't make any issue on prod still I have added a check to resolve this issue for older invoices as well.
It seems working fine now, you may try it again after the latest code deployment.

**Comment by wes-otf** [comment]
For some reason now whenever I go to `/apply/projects/invoices/` on test I get a 500 page cause by the error: 
```
Missing staticfiles manifest entry for 'js/apply/jquery.fancybox.min.js'
```
Which is weird, was there an issue with `collectstatic` on the deploy or something?

**Comment by frjo** [comment]
@wes-otf I missed doing a rebase for this PR, we have recently flatten the dir structure in another PR.

Should be fixed now.

**Pull request merged**
