### PR TITLE
Remove fancybox modal for invoicing and reporting

### PR DESCRIPTION
**Pull request by sandeepsajan0**
Fixes #ISSUEID

- [ ] Use htmx/alpine for Invoice status update modal
- [ ] Use htmx/alpine for report frequency update modal
- [ ] Use htmx/alpine for Update project status modal( Closing and Complete)
- [ ] Use htmx/alpine for lead update modal
- [ ] Use htmx/alpine for project title modal
- [ ] Remove fancybox for report save, sabmit and skip confirmation.
- [ ] Remove fancybox imports from project code

## Test Steps

 - [ ] …

### CODE REVIEW

**Comment by frjo** [comment]
@sandeepsajan0 Needs a rebase after I merged in your other PR.

**Comment by sandeepsajan0** [comment]
@frjo I have moved the column "invoice_number" to first col. I think it looks good now.
image

**Comment by frjo** [comment]
@wes-otf I have you found any issues regarding these dialogs? Would be good to get it merged if it works well. Then we can finish up https://github.com/HyphaApp/hypha/pull/4226.

**Comment by wes-otf** [comment]
No issues in my testing so far, nice implementation @sandeepsajan0!

**Pull request merged**
