### PR TITLE
Unarchive the archived Submissions

### LINKED ISSUE #3047: Function to unarchive single submission and show submission is archived
- [ ] Add "Unarchive" button on submission detail view in "Actions to take"
- [ ] Add banner submission detail view if archived
- [ ] Remove actions not needed for archived submissions. Like add review, change status etc.

Related https://github.com/HyphaApp/hypha/issues/2996

### PR DESCRIPTION
**Pull request by sandeepsajan0**
Fixes #3047 

Add description here.

### CODE REVIEW

**Review by frjo — APPROVED** [review]

**Comment by sandeepsajan0** [comment]
@frjo We can put it on test again with the latest changes, as I have updated the code for [small issues I noticed](https://github.com/HyphaApp/hypha/pull/3003#issuecomment-1346415417) on test site.

**Comment by frjo** [comment]
I might have done something to break this PR @sandeepsajan0. Can you take a look at the failing test please.

I have merged in the archive PR to main.

**Comment by frjo** [comment]
I have just merged in https://github.com/HyphaApp/hypha/pull/3075 so the migrations will need some updates.

**Comment by sandeepsajan0** [comment]
@frjo There was a problem with the `dispatch` method, at the time of getting the object. I am not sure why these tests were not failing before or it might have happened because of rebasing. Actually, I also got many conflicts on rebasing it with the main branch. 
I don't know why it is picking up some of the Archive PR #3003 commits(looks weird) but file changes are the same as before. 
I think we should put it on the test first?

**Pull request merged**
