### PR TITLE
Text updates/changes noticed in user testing. 

### LINKED ISSUE #3448: Suggestions from the project's user testing
**Part-1(miro board cards)**:
- [x] PAF waiting for approval table shouldn't show if no project in any tab.
- [x] Show requested by as well in PAF Approvals(sidebar). Right now only Pending and Approved are showing.
- [x] Remove the converted option from the invoice.
- [x] Show activities on the Invoice page.
- [x] Show price in US format.
- [x] Downloaded PAF add dates along with approver names, sync it with platform.
- [x] "Add Invoice' as next step even after invoice creation(remove next step after one invoice).
- [x] Add hyperlinks to comments and use those links for scrolling(request change comments)

**Part-2(figma design changes)**
- [x] #3458
- [x] #3462 
- [x] #3467
- [x] #3469
- [x] Update invoice table column name on project detail page, "Submitted" to "Date Submitted".
- [x] Update "Reporting" section header to "Reports".
- [x] Change Upload Contract modal "submit" button text to "Upload" for Applicant.
- [x] Update Next step text for "Awaiting Contract approval from Staff" to ".... approval by org_short_name"(for applicant role).
- [x] In "Submit for Approval" or "Resubmit" PAF modal, make optional line bold and update the text as per design.
- [x] "Invoice Uploaded" to "Invoice added" in alert/success message text on invoice creation.
- [x] "Create Invoice" to "Add invoice" on invoice form heading.
- [x] Update next step for applicant during PAF approval process, set it to a single/fix text.(see design for text)
- [x] Update Admin bar's "Download" button text fot PAF and SOW to "Download PAF" and "Download SOW".
- [x] Update PAF edit page submit button text to Save.
- [x] Update "Invoice created" to "Invoice added" in activities.
- [x] "View <related_object>" in activity feed instead of just <related_object>. Ex: Contract -> View Contract
- [x] "Edit" and "Delete" to "Edit Invoice" and "Delete Invoice" on the Invoice detail page.
- [x] Update applicant to vendor at every place in projects.
- [x] #3474
- [x] #3479
- [x] #3477
- [x] Update Approval section of PAF detailed page/pdf. Show as per PAF approvals sidebar section(include pending and request changes).
- [x] #3480
- [x] #3494
- [x] #3495
- [ ] - [ ] Make comment required if a user selects request_changes on updating paf status.

### PR DESCRIPTION
**Pull request by sandeepsajan0**
Refs #3448(Part-2) 

- [ ] Update invoice table column name on project detail page, "Submitted" to "Date Submitted".
- [ ] Update "Reporting" section header to "Reports".
- [ ] Change Upload Contract modal "submit" button text to "Upload" for Applicant.
- [ ] Update Next step text for "Awaiting Contract approval from Staff" to ".... approval by org_short_name"(for applicant role).
- [ ] In "Submit for Approval" or "Resubmit" PAF modal, make optional line bold and update the text as per design.
- [ ] "Invoice Uploaded" to "Invoice added" in alert/success message text on invoice creation.
- [ ] "Create Invoice" to "Add invoice" on invoice form heading.
- [ ] Update next step for applicant during PAF approval process, set it to a single/fix text.
- [ ] Update Admin bar's "Download" button text fot PAF and SOW to "Download PAF" and "Download SOW".
- [ ] Update PAF edit page submit button text to Save.
- [ ] Update "Invoice created" to "Invoice added" in activities.
- [ ] "View <related_object>" in activity feed instead of just <related_object>. Ex: Contract -> View Contract
- [ ] "Edit" and "Delete" to "Edit Invoice" and "Delete Invoice" on the Invoice detail page.
- [ ] Update applicant to vendor at every place in projects.

### CODE REVIEW

**Comment by fourthletter** [comment]
Refs #3448(Part-2) 

- [x] Update invoice table column name on project detail page, "Submitted" to "Date Submitted".
- [x] Update "Reporting" section header to "Reports".
- [x] Change Upload Contract modal "submit" button text to "Upload" for Applicant.
- [x] Update Next step text for "Awaiting Contract approval from Staff" to ".... approval by org_short_name"(for applicant role).
- [x] In "Submit for Approval" or "Resubmit" PAF modal, make optional line bold and update the text as per design.
- [x] "Invoice Uploaded" to "Invoice added" in alert/success message text on invoice creation.
- [x] "Create Invoice" to "Add invoice" on invoice form heading.
- [x] Update next step for applicant during PAF approval process, set it to a single/fix text.
- [x] Update Admin bar's "Download" button text fot PAF and SOW to "Download PAF" and "Download SOW".
- [ ] Update PAF edit page submit button text to Save.
- [x] Update "Invoice created" to "Invoice added" in activities.
- [x] "View <related_object>" in activity feed instead of just <related_object>. Ex: Contract -> View Contract
- [x] "Edit" and "Delete" to "Edit Invoice" and "Delete Invoice" on the Invoice detail page.
- [ ] Update applicant to vendor at every place in projects.

**Comment by fourthletter** [comment]
- [ ] Update Next step text for "Awaiting Contract approval from Staff" to ".... approval by org_short_name"(for applicant role).

'Hypha' because it's on the test site...

image

**Comment by fourthletter** [comment]
- [ ] Update PAF edit page submit button text to Save.

I do not see this on test PAF https://test-apply.hypha.app/apply/projects/54/edit/

**Comment by fourthletter** [comment]
- [ ] Update applicant to vendor at every place in projects.

I'm not sure where this change occurred, comment on project page still say 'applicant'

image

**Comment by fourthletter** [comment]
@sandeepsajan0 This was AMAZING -- thank you so much for polishing this. 🎊

**Comment by fourthletter** [comment]
@abhiXII looping you in

**Comment by abhiXII** [comment]
1. Change Submit to Upload for Contracting also 
image

Can we also change the upload button with icon to `Select contract` and remove the Contract text there? Or even call it Select file since there's too many upload now.


2. Let's use sentence case for titles like `Date submitted`? Shall we also change it in all the invoice tables? like this one on project page:
image
And this one on finance dashboard. 
image
If you want, we can also come back to this when to update all the tables as a part of dashboard design work.


3. Do we want to say Hypha or OTF. Since Hypha is not the organisation, we should say OTF. 
image
Does this need to be changed on Wagtail? Or maybe it will show OTF on live?


Others look good. Thank you!

**Comment by fourthletter** [comment]
@abhiXII - Could we please change the text to something else besides **"Corrections/amendments?**" 

I think we should take this out completely since it's not even good ux. If a vendor wants to communicate with someone at OTF, they should know how to already at this stage.

image

**Comment by abhiXII** [comment]
Makes sense @fourthletter! thanks for the prompt. 
What about this — at most, we can show a text in the tooltip to "use communications tab to request any corrections or amendments"
image

But if we expect the vendors to know, then we can just remove the tooltip too. there's too many tooltips here

**Comment by sandeepsajan0** [comment]
> 1. Change Submit to Upload for Contracting also

I think we decided it for Applicant only because they already have another submit button, but for Contracting it is the only submit option.

> Can we also change the upload button with icon to Select contract.

Actually, It is general in our system to use 'Upload' for every file field. And it requires some work, we need to override a few things only for the contract part. That's why I kept it on hold. It is also not a big issue so we can come back to it later?

> 2. Let's use sentence case for titles like Date submitted? Shall we also change it in all the invoice tables? like this one on project page:

Sure, not a big deal. It can be updated everywhere. But regarding the sentence case, we have 'Invoice Number'(next to Date submitted) in title case that's why I tried to keep things similar. We want to update all other table headings as well or only the Date submitted?

> 3. Do we want to say Hypha or OTF. Since Hypha is not the organisation, we should say OTF.

'Hypha' is the organization name(Short name) on the test site. If we will change it to OTF, it will show OTF. It is not hard coded.

**Comment by frjo** [comment]
> Actually, It is general in our system to use 'Upload' for every file field. And it requires some work, we need to override a few things only for the contract part. That's why I kept it on hold. It is also not a big issue so we can come back to it later?

It should be the same everywhere. No hacks for particular corners of Hypha. We go with one or the other in all instances.

> But regarding the sentence case, we have 'Invoice Number'(next to Date submitted) in title case that's why I tried to keep things similar. We want to update all other table headings as well or only the Date submitted?

We should remove sentence case wherever we encounter it from now on.

**Comment by abhiXII** [comment]
Yeah I think let's keep it same everywhere for consistency and find other ways to communicate those nuances. In fact I myself keep forgetting such design decisions.

oh yeah let's use sentence case everywhere, like you can just change it to Invoice number also when you spot. Same for anywhere we see and slowly the entire system will be sentence case. 

Yeah, better to change it to OTF I think

**Pull request merged**
