### PR TITLE
Implement DJP: Django Plugins.

### PR DESCRIPTION
**Pull request by frjo**
Read up on DJP at https://djp.readthedocs.io/

### CODE REVIEW

**Comment by theskumar** [comment]
Looks good.

**Comment by theskumar** [comment]
You can also add folder based discovery, so if someone drop a plugin a specific folder it will be automatically picked up. 

Benefit I see you don't do installed them.

**Comment by theskumar** [comment]
> You can also add folder based discovery, so if someone drop a plugin a specific folder it will be automatically picked up.
> 
> Benefit I see you don't do installed them.

I thought it needed any configuration in host application, but looks like nothing needs to be done. 

https://djp.readthedocs.io/en/latest/installing_plugins.html#loading-plugins-from-a-directory

**Comment by wes-otf** [comment]
Going to do some studying up on this in the next coming weeks but this looks good!

**Pull request merged**
