### PR TITLE
Update Project Invoicing

### LINKED ISSUE #2354: Update project invoicing
This story is part of epic #2352.

## User Story

> As a funded project leader, I want to submit an invoice for my fixed-price contract project, so that I can receive payment.

### Demo
**NB:** This demo needs to be updated with new designs. This simple demo explains how the contractor would create and submit an invoice request. 
https://user-images.githubusercontent.com/1899506/121354966-b14a1400-c92f-11eb-89e9-54c97e172026.mp4

#### 2.1
When the contractor wants to submit an invoice they will log into Hypha, and go to their in-progress project.
This contractor is working on the Maya Summit Project. They want to add an invoice so they click on Add invoice. This starts the invoice creation process. 

#### 2.2 
They have to add the required dates, invoice amount, and the currency. Right now we are only required to support US Dollars, but in the future possibly other.

#### 2.3
They upload the invoice file - which must be a pdf.

#### 2.4
Then the contractor can add the supporting documents, these are files that are related to the invoice. They could be xls, microsoft office documents, open office documents, pdfs, txt files. They can add multiple files. They can delete each file if they need to.

#### 2.5
The contractor can add an optional note to the invoice. When they are ready they can submit the invoice. 

#### 2.6  
When the invoice is successfully submitted, they can confirmation it’s submitted.
From here they can go back to the project detailed view.

#### 2.7
On the project detailed view, they can see the submitted invoice.

**Minimum-viable story**

This minimum viable story works for OTF's instance, and for Hypha-core. For the fixed-price contract the project needs to submit the following minimum information:

- date from covered in the payment request
- date to covered in the payment request
- the total amount of money requested (in dollars)
- upload multiple files (spreadsheet, pdf, doc, txt file, png, jpg)
  - this is to provide files for 1) their invoice, and 2) the evidence the work has been completed
- free text comment

**Priority**

- High (keeping you from completing day-to-day tasks)

**Affected roles**

- Staff
- Applicants

**Ideal deadline**

Approx. June 2021

### PR DESCRIPTION
**Pull request by sks444**
Fixes https://github.com/HyphaApp/hypha/issues/2354

### CODE REVIEW

**Comment by sks444** [comment]
@frjo, this branch is rebased on top of Add Vendor https://github.com/HyphaApp/hypha/pull/2401; And adds the invoicing feature mentioned in https://github.com/HyphaApp/hypha/issues/2354

This could also be deployed on test to test out the invoicing feature.

I have not yet removed Payment Requests models etc..it would be easier to remove them when we have completed the flow with Invoicing(i.e. [approval](https://github.com/HyphaApp/hypha/blob/5a2ca90e4183e70442b3f9eb5f291a1b908e9cbc/hypha/apply/projects/models/payment.py#L35) etc.)..as then Payment Requests models won't have any references at other places.

I have also added the feature to update invoice status..which I see was not mentioned in https://github.com/HyphaApp/hypha/issues/2354, let me know if we need to disable it for this pr..we can test that out later when we work on the next stage of invoicing.

**Comment by frjo** [comment]
@sks444 I have committed https://github.com/HyphaApp/hypha/pull/2401 now so this can be rebased of main and then I can deploy it to test.

**Comment by sks444** [comment]
Done @frjo.

We can deploy this feature to test for testing.

I will fix the failing tests in the meantime.

**Comment by frjo** [comment]
Deploying to test now.

**Comment by sks444** [comment]
@frjo, have fixed the tests now.

**Comment by frjo** [comment]
Deployed the latest to test now.

**Comment by frjo** [comment]
@sks444 This has been on test for some time and it seems to work as it should. Can we merge this in to main now or do you want to add more to it first?

**Comment by sks444** [comment]
@frjo, Yes, this can be merged, thanks!

**Pull request merged**
