### PR TITLE
Average total score in review and assignee box

### LINKED ISSUE #3340: Display average total score in the Reviews & assignee's box
**Is your feature request related to an existing functionality? Please describe.**

On the Submission Details page, add Average Total Score (displaying the average of all total review scores) to the Reviews & assignee's box.

**Priority**

- Low priority

**Affected roles**

- Staff
- Admin
- Reviewers

### PR DESCRIPTION
**Pull request by gmurtaza00**
Added Average total score in the Reviews & assignee's box.

image

Closes #3340

### CODE REVIEW

**Review by frjo — APPROVED** [review]

**Review by theskumar — CHANGES_REQUESTED** [review]
@frjo @gmurtaza00 I tried with alternate position of the avg. score display. Thoughts? 

Screenshot 2023-04-20 at 06 50 39@2x

This is diff you'll need to apply for this look. 

```diff
diff --git a/hypha/apply/funds/templates/funds/includes/review_sidebar.html b/hypha/apply/funds/templates/funds/includes/review_sidebar.html
index 020e01b40..fc81143b3 100644
--- a/hypha/apply/funds/templates/funds/includes/review_sidebar.html
+++ b/hypha/apply/funds/templates/funds/includes/review_sidebar.html
@@ -1,12 +1,15 @@
 {% load i18n review_tags %}
 
-<ul class="reviews-sidebar" x-data='{showHiddenReviewers: false}'>
-    <li class="reviews-sidebar__item reviews-sidebar__item--header">
-        <div></div>
-        <div>{{ recommendation|traffic_light }}</div>
-        <div></div>
-    </li>
+<div class="flex items-center justify-around px-2 py-1 bg-gray-100">
+    <span>
+        {{ recommendation|traffic_light }}
+    </span>
+    <span class="font-medium">
+        {% trans 'Avg. Score'%}: {{assigned_reviewers|average_review_score|floatformat:'1'}}
+    </span>
+</div>
 
+<ul class="reviews-sidebar mt-4" x-data='{showHiddenReviewers: false}'>
     {% if not staff_reviewers_exist %}
         <li class="reviews-sidebar__no-reviews">{% trans "No staff reviewers yet" %}</li>
         <hr class="reviews-sidebar__split">
@@ -42,13 +45,4 @@
             {% endif %}
         {% endfor %}
     {% endfor %}
-    <hr>
-    <div class="reviews-sidebar__item">
-        <div class="reviews-sidebar__extend-column">
-            {% trans 'Average Total Score'%}
-        </div>
-        <div>
-            {{assigned_reviewers|average_review_score|floatformat:'1'}}
-        </div>
-    </div>
 </ul>
diff --git a/hypha/static_src/src/sass/apply/components/_reviews-sidebar.scss b/hypha/static_src/src/sass/apply/components/_reviews-sidebar.scss
index 58c0f75c7..44a5bb753 100644
--- a/hypha/static_src/src/sass/apply/components/_reviews-sidebar.scss
+++ b/hypha/static_src/src/sass/apply/components/_reviews-sidebar.scss
@@ -108,9 +108,4 @@
     &__split {
         margin-bottom: 20px;
     }
-
-    &__extend-column {
-        grid-column-start: 1;
-        grid-column-end: 3;
-    }
 }

```
-------------

Apart from the above change request. There are few things I noted that leads to the overall change in positioning.

1. "Average Total Score" was too verbose, could a "Avg. score" work as well? 
2. The font weight of the "Average Total Score" matched with the section header "Reviews and Assignee"
3. There bottom was getting too crowded with "Show more..." and this avg display.
4. The overall status is displayed at two places: top with traffic light and then at the bottom with avg. score. 
5. The html element mixed "ul -> li' with "div" instead of "li".

**Comment by frjo** [comment]
I like using the empty space next to the traffic light.

Could we not even shrink the text down to just "Avg."? Then is is short enough to allow the columns to line up with the other scores.

**Comment by gmurtaza00** [comment]
@frjo @theskumar Which one should be finalized, the one with **Avg. Score** or **Avg**?

image


Screenshot from 2023-04-25 10-49-01

**Comment by frjo** [comment]
@gmurtaza00 Let go with "Avg. Score".

**Review by theskumar — APPROVED** [review]

**Comment by frjo** [comment]
@gmurtaza00 Can you remove the left over scss and then I can merge this in. Nice work and thanks for sticking with all our comments and suggestions.

https://github.com/HyphaApp/hypha/blob/9d6ae7f393cd71ef1210a1e09dce739e020565bd/hypha/static_src/src/sass/apply/components/_reviews-sidebar.scss#L54-L58

**Review by frjo — CHANGES_REQUESTED** [review]
See other comment.

**Review by frjo — APPROVED** [review]

**Pull request merged**
