### PR TITLE
Bugfix: Determination creation UI does not use default messages

### LINKED ISSUE #2455: Determination Templates Not Implemented
**Describe the bug**

There is functionality for the user to add determination message templates but those templates are not imported when the user creates a determination for an application. 

**To Reproduce**
1. Create determination template messages.
2. Add a determination to an application.

**Expected behavior**

I expect that those determination template messages would populate the text editor. 

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff
- Reviewers

**Additional context**
Patch inbound.

### PR DESCRIPTION
**Pull request by hawkinsw**
In Hypha, the user has the ability to create default determination
messages. These messages were not being properly populated in the UI
shown when creating a determination for an application. This change
fixes that bug.

Fixes #2455

### CODE REVIEW

**Comment by frjo** [comment]
There are some code style issues in the js code, please run "gulp lint:js" and have a look at it.

As seen in the test above there is one python code style issue as well as a failing test.

I believe the test error comes from the legacy hard coded determinations forms.

**Comment by hawkinsw** [comment]
Hey @frjo !! Sorry for not be fast on fixing this up. I promise I am working on it :-) I appreciate the feedback and I am really excited to contribute. I hope that what I am doing is helpful!

**Comment by frjo** [comment]
@hawkinsw The reason I made the code style fixes is that this would be really nice to get committed. So definitely helpful!

**Review by frjo — DISMISSED** [review]
See below

**Review by frjo — CHANGES_REQUESTED** [review]
The tests need to pass.

**Pull request closed without merging**
