### PR TITLE
Feature/879 api tests

### LINKED ISSUE #879: API: Tests
Tests for all implemented API endpoints

### LINKED ISSUE #880: API: Deployment and config
Deployment, configuration and tidy up of where files live

### PR DESCRIPTION
**Pull request by todd-dembrey**
This covers the changes from #879 and #880 

Fixes #879
Fixes #880

I have moved the API files into a separate app and versioned them under `v1`

We will need to update the `API_BASE_URL` when deploying this.

I'm in the process of writing some tests for the API for #879. Hence the WIP

### CODE REVIEW

**Comment by frjo** [comment]
@todd-dembrey Anything stopping us from deploying this? Seems to work well and I have just rebased from master and updated it for comment editing.

**Comment by todd-dembrey** [comment]
Apart form it is lacking any tests! :)

The reason for the delay is #1633 - i got a bit carried away trying to make the workflows separate from the model definitions which is required for others to define their own workflows and to generally simplify the testing of the application without relying on the master OTF flow definition. 

It was really beyond the scope of this ticket.

**Comment by saoun** [comment]
@todd-dembrey any updates on this and how/when we can deploy?

**Comment by todd-dembrey** [comment]
see comments:
https://github.com/OpenTechFund/hypha/issues/880#issuecomment-581973067
https://github.com/OpenTechFund/hypha/issues/879#issuecomment-581972576

Propose this ticket closes #880 and #879 is not in progress.

**Pull request merged**
