### PR TITLE
Update authentication and registration forms

### PR DESCRIPTION
**Pull request by theskumar**
## What's changed: 

Admin:
- "User Setting" is now "Auth Settings", this setting is also now a global settings, as opposed to site specific earlier.

Register form:
- Add user consent to the register form (customizable)
- Allow adding custom extra text to register form

Login Form:
- Add create account link

Forgot password: 
- Add link to login on forgot password form

This PR is against the remove-public-nav as this where we started to use tailwind on the login/register pages. This PR also remove the top admin bar from the public pages, making it look much better.

Ref: #3443 

## Login
This should "Create account" if registration is enabled. Also, forgot password link is moved at the bottom. 
Screenshot 2023-06-25 at 19 18 35@2x

## Register
Screenshot 2023-06-25 at 19 20 12@2x
1. Question and link to login. 
2. User consent (same as displayed on the login form)
3. custom text for register

## Two factor
Added title, and moved the use backup code at the bottom.
Screenshot 2023-06-25 at 19 23 49@2x

## Admin

Screenshot 2023-06-25 at 19 26 58@2x

### CODE REVIEW

**Review by frjo — APPROVED** [review]

**Comment by frjo** [comment]
Trying to test this I get:

```
psycopg2.errors.UndefinedTable: relation "users_authsettings" does not exist
LINE 1: ..., "users_authsettings"."register_extra_text" FROM "users_aut...

django.db.utils.ProgrammingError: relation "users_authsettings" does not exist
LINE 1: ..., "users_authsettings"."register_extra_text" FROM "users_aut...

```

**Comment by frjo** [comment]
I like how it looks in the screenshots!

**Comment by theskumar** [comment]
If you were able to resolve the migration issues, looks like you just need to run the latest migrate command. The `register_extra_text` is added in this migration file: https://github.com/HyphaApp/hypha/pull/3457/files#diff-a61a335a682e4aa1bd9d7359c8dd3ad9d1d91088d2ac1436b884ee863c297cf3R22-R26

It should be safe to merge this PR as it is against the below:
- https://github.com/HyphaApp/hypha/pull/3432

**Comment by frjo** [comment]
Not able to resolve the migration issue, looks like this whatever I do.

~~~~
Traceback (most recent call last):
  File "…/hypha/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "users_authsettings" does not exist
LINE 1: ..., "users_authsettings"."register_extra_text" FROM "users_aut...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "…/hypha/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "…/hypha/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "…/hypha/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "…/hypha/venv/lib/python3.11/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "…/hypha/venv/lib/python3.11/site-packages/django/core/management/base.py", line 393, in execute
    self.check()
  File "…/hypha/venv/lib/python3.11/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "…/hypha/venv/lib/python3.11/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "…/hypha/venv/lib/python3.11/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "…/hypha/venv/lib/python3.11/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "…/hypha/venv/lib/python3.11/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "…/hypha/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "…/hypha/venv/lib/python3.11/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "…/hypha/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "…/hypha/hypha/urls.py", line 13, in <module>
    from hypha.apply.users.urls import public_urlpatterns as user_urls
  File "…/hypha/hypha/apply/users/urls.py", line 6, in <module>
    from .views import (
  File "…/hypha/hypha/apply/users/views.py", line 53, in <module>
    class RegisterView(View):
  File "…/hypha/hypha/apply/users/views.py", line 54, in RegisterView
    form = CustomUserCreationForm()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "…/hypha/hypha/apply/users/forms.py", line 49, in __init__
    self.user_settings = AuthSettings.load(request_or_site=self.request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "…/hypha/venv/lib/python3.11/site-packages/wagtail/contrib/settings/models.py", line 191, in load
    return cls._get_or_create()
           ^^^^^^^^^^^^^^^^^^^^
  File "…/hypha/venv/lib/python3.11/site-packages/wagtail/contrib/settings/models.py", line 172, in _get_or_create
    first_obj = cls.base_queryset().first()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "…/hypha/venv/lib/python3.11/site-packages/django/db/models/query.py", line 674, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "…/hypha/venv/lib/python3.11/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "…/hypha/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "…/hypha/venv/lib/python3.11/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "…/hypha/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "…/hypha/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "…/hypha/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "…/hypha/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "…/hypha/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "…/hypha/venv/lib/python3.11/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "…/hypha/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "users_authsettings" does not exist
LINE 1: ..., "users_authsettings"."register_extra_text" FROM "users_aut...
~~~~

**Comment by theskumar** [comment]
Ok, if the PR overall looks good, I'll have it as part of the #3432 and build fresh set of migrations

**Pull request merged**
