### PR TITLE
Hide Project task and project settings if projects is disabled

### LINKED ISSUE #3906: Hide Project items in Wagtail if not enabled
When `PROJECTS_ENABLED=false`, configuration for projects should be hidden in Wagtail. Things like menu items & PAF options in fund configuration should not be visible.

### PR DESCRIPTION
**Pull request by sandeepsajan0**
Fixes #3906 

image

## Test Steps

 - [ ] …

### CODE REVIEW

**Comment by theskumar** [comment]
@sandeepsajan0 you'll need to resolve/rebase this pr.

**Comment by frjo** [comment]
@sandeepsajan0 This can now be rebased on top of main.

**Comment by frjo** [comment]
This can also be rebased on main.

**Comment by sandeepsajan0** [comment]
@frjo It is rebased with main now.

**Pull request merged**
