### PR TITLE
Task is not removed for staff while project moved to next stage

### LINKED ISSUE #3946: When Project Form is submitted by someone that isn't the lead, to do notification stays in lead's todo
If the Project Form is submitted by a user that isn't the project lead, the `Project ... is waiting for PAF submission` notification will remain in the lead's To-Do list despite the Project Form being submitted. This was done with no PAF Reviewers set so I wonder if it's related to #3881?

### PR DESCRIPTION
**Pull request by sandeepsajan0**
Fixes #3946 

## Test Steps

 - [ ] …

### CODE REVIEW

**Comment by wes-otf** [comment]
Hey @sandeepsajan0 I don't think the tasks show up in my task list anymore - I just create a new project and make sure the fund has a valid Project Form set & I'm the lead right?

**Comment by sandeepsajan0** [comment]
@wes-otf Sorry for the late response, I missed it somehow.
>I just create a new project and make sure the fund has a valid Project Form set & I'm the lead right?

Project creation creates a task for all staff members(exact) and I think your account might have other roles like staff admin, try/check it with any staff account. Ideally, only staff members will be dealing as project leads and we have some hard/exact role checks in project side because of PAF reviewer roles.

**Comment by wes-otf** [comment]
@sandeepsajan0 this worked for me! my only thoughts are that only staff that are leads on a project should have it appear in their task list. At least with how many projects OTF has I could see it bogging down the tasks lists. @frjo @Techslammer any thoughts?

**Comment by frjo** [comment]
@wes-otf If OTF want to change who gets the task I think a new issue is the place for that.

If this PR removes the task as it should we might approve it.

**Comment by wes-otf** [comment]
that sounds good to me! I'll open another issue

**Pull request merged**
