### PR TITLE
Part 1 New screening status: Add yes/no and default field

### PR DESCRIPTION
**Pull request by sks444**
Towards https://github.com/OpenTechFund/hypha/issues/1948
Related to https://github.com/OpenTechFund/hypha/pull/2148

See wireframes here: https://github.com/OpenTechFund/hypha/issues/2158

### CODE REVIEW

**Review by Parbhat — APPROVED** [review]
Looks good. @frjo It will help in easier data migration later from old screening status to new screening statuses. More details in https://github.com/OpenTechFund/hypha/issues/1948#issuecomment-719350780

**Comment by frjo** [comment]
Added link to wireframes from @ei8fdb https://github.com/OpenTechFund/hypha/issues/2158

**Comment by frjo** [comment]
Please bring @ei8fdb in whenever you have UX questions.

**Comment by ei8fdb** [comment]
Hi @parbhat @sks444 if you have any questions (**any!**) about the designs, or if there is any alternative we need to discuss (e.g. This is possible, but will take a looong time, is there another possibility?), tag me here. I'm happy to discuss alternatives, explain things if they're unclear.

**Comment by Parbhat** [comment]
Sure @ei8fdb, thanks. We will be in touch for inputs.

**Review by frjo — APPROVED** [review]
Looks good! Clean and simple.

**Comment by Parbhat** [comment]
@frjo It would be good to merge this PR as it will help to proceed to the next steps.

**Pull request merged**
