### PR TITLE
Add grey background for applicant dashboard

### PR DESCRIPTION
**Pull request by sandeepsajan0**
Current background:
image

Updated version:
image

### CODE REVIEW

**Review by theskumar — APPROVED** [review]

**Comment by theskumar** [comment]
@sandeepsajan0 this PR still in draft, do you want to mark as ready for review?

**Review by frjo — APPROVED** [review]

**Comment by frjo** [comment]
Needs a rebase.

**Comment by frjo** [comment]
A merge conflict with https://github.com/HyphaApp/hypha/pull/3587 so will hold this PR until that has merged.

**Comment by sandeepsajan0** [comment]
@frjo This PR is ready to put on the test site.

**Comment by sandeepsajan0** [comment]
@frjo I have updated the PR, use the body class block to add background color instead of adding `bg-light-grey` class to the wrapper directly. We can put the latest version to test site.

**Comment by frjo** [comment]
Removing this from testing for now, got merge conflicts with the other PRs.

**Pull request merged**
