### PR TITLE
Add activity e-mail digest for each Fund and Lab

### LINKED ISSUE #3017: Add activity e-mail digest for each Fund and Lab
### User Story

As a Program Manager (staff user), I would like more granular control over which emails I received from Hypha. Existing categories or sub-headings in the email digest include Submissions, Comments, Other activities. As a user I would like to only receive emails related to submissions.

### Proposed Solution

- [ ] Add an "Digest recipient e-mails" field to each Fund and Lab. Similar to the existing Slack channel field.
- [ ] Create the same type of digest as the global one but filtered for each Fund and Lab.
- [ ] Send out all digest with the same cron command

### PR DESCRIPTION
**Pull request by theskumar**
Fixes #3017

- [x]  Add an "Digest recipient e-mails" field to each Fund and Lab. Similar to the existing Slack channel field.
- [x]  Create the same type of digest as the global one but filtered for each Fund and Lab.
- [x]  Send out all digest with the same cron command.

---

Screenshot 2022-11-03 at 08 38 25@2x

### CODE REVIEW

**Review by frjo — APPROVED** [review]

**Comment by frjo** [comment]
Migration conflict with #3003 that is on test now. Wait until that is approved and then rebase this PR again.

**Comment by fourthletter** [comment]
I receive an email digest but don't think it's fund specific yet.

image

**Comment by theskumar** [comment]
Can you double-check if your email was added to the fund configuration?

**Comment by fourthletter** [comment]
I tested and it works! Thank you!

image

**Pull request merged**
