### PR TITLE
Replace flake8 & isort with ruff

### LINKED ISSUE #3101: Consider replacing flake8 and iSort with ruff
Ruff is a replacement for flake8, implemented in rust for performance. It supports many flake8 plugins by default and is compatible with iSort and black.

The downside is that we might use some flake8 plugins, but this project does not use many flake8 plugins or intend to use more.

See: https://github.com/charliermarsh/ruff#how-does-ruff-compare-to-flake8

### PR DESCRIPTION
**Pull request by theskumar**
Fixes #3101

- Remove `make sort` and `make sort-fix` make targerts
- Use `make lint` and `make lint-fix` instead.
- Make use of GitHub Annotation to surface issues as annotations directly in the files changed, similar to CodeQL.
- Move stuff from `setup.cfg` to `pyproject.toml`
- Fixed the potentially buggy code. Each of the fix types is in individual commits.

### CODE REVIEW

**Review by frjo — CHANGES_REQUESTED** [review]
Looks good! Possible to have the pyproject file in yaml instead of toml. I find them easier to read and most other conf files in Hypha are yaml.

**Comment by theskumar** [comment]
pyproject.toml is the new standard for describing project metadata description to replace `setup.*`, first introduced in [PEP 518](https://peps.python.org/pep-0518/) and later expanded in [PEP 517](https://peps.python.org/pep-0517/), [PEP 621](https://peps.python.org/pep-0621/) and [PEP 660](https://peps.python.org/pep-0660/). So, unfortunately, it's here to stay. 

Subsequently, Python 3.11 included toml lib as part of standard lib. 

> This format was chosen as it is human-usable (unlike JSON [[7]](https://peps.python.org/pep-0518/#id20)), it is flexible enough (unlike configparser [[9]](https://peps.python.org/pep-0518/#id22)), stems from a standard (also unlike configparser [[9]](https://peps.python.org/pep-0518/#id22)), and it is not overly complex (unlike YAML [[8]](https://peps.python.org/pep-0518/#id21)). The TOML format is already in use by the Rust community as part of their Cargo package manager [[14]](https://peps.python.org/pep-0518/#cargo) and in private email stated they have been quite happy with their choice of TOML. A more thorough discussion as to why various alternatives were not chosen can be read in the [Other file formats](https://peps.python.org/pep-0518/#other-file-formats) section. The authors do realize, though, that choice of configuration file format is ultimately subjective and a choice had to be made and the authors prefer TOML for this situation.

**Comment by theskumar** [comment]
Rebased with main and fixed the potentially buggy code. Each of the fix types is in individual commits.

**Review by frjo — APPROVED** [review]

**Comment by frjo** [comment]
Deploying this on test now.

**Comment by frjo** [comment]
@theskumar  Just when you have rebased I went in and merged in another set of PR:s.

This looks really good however and ruff is silly fast compered to flake and isort. A bit like Hugo vs Jekyll.

**Comment by theskumar** [comment]
Rebased and resolved merge conflicts.

**Pull request merged**
