### PR TITLE
Sorting header applied on more submissions tables

### PR DESCRIPTION
**Pull request by bickelj**
Issue #3973

## Test Steps

- Visit `submissions/reviews`
- Sort the submissions by any column

### CODE REVIEW

**Review by frjo — CHANGES_REQUESTED** [review]
The admin view shows to much, adds batch actions etc. Not suitable for reviewers.

I suggest instead setting `orderable = True` for `ReviewerSubmissionsTable`.

**Comment by bickelj** [comment]
> The admin view shows to much, adds batch actions etc. Not suitable for reviewers.
> 
> I suggest instead setting `orderable = True` for `ReviewerSubmissionsTable`.

It seems to work, nice clean suggestion!

Edit: but oh, no, tests fail:
```
FAILED hypha/apply/dashboard/tests/test_views.py::TestReviewerDashboard::test_no_submissions_waiting_for_review - TypeError: Cannot reorder a query once a slice has been taken.
FAILED hypha/apply/dashboard/tests/test_views.py::TestReviewerDashboard::test_submission_assigned_but_not_in_external_review_status - TypeError: Cannot reorder a query once a slice has been taken.
FAILED hypha/apply/dashboard/tests/test_views.py::TestReviewerDashboard::test_waiting_for_review_with_count - TypeError: Cannot reorder a query once a slice has been taken.
```

**Comment by bickelj** [comment]
The slice it's referring to (at least for the first test) is a limit from `hypha/apply/dashboard/views.py` in `ReviewerDashboardView.awaiting_reviews`:
```python
            "table": ReviewerSubmissionsTable(submissions[:limit], prefix="my-review-"),
```
Removing the limit lets the test pass but that is obviously not the correct solution. We need to reorder the operations such that the limit comes last, I suppose.

**Comment by frjo** [comment]
We are replacing all old submission tables, see https://github.com/HyphaApp/hypha/pull/4080.

So I'm closing this one.

**Pull request closed without merging**
