### PR TITLE
Fix save as draft and allow saving without required fields

### LINKED ISSUE #3556: For logged in applicant, messaging after an application submission as draft
**Describe the bug**

For logged in user, when saving the application as draft the success message assumes the user is still not logged in and inform the user about the email being send but there is not actual email being sent.

Also, when the message is displayed and if you try to refresh the page the system will create multiple drafts.

**To Reproduce**

1. Go to application form
2. Click on 'Save Draft'
3. Check the success message.

**Expected behavior**

- If the user is already logged in the message should not include the message that an email is sent.
- On successfully saving as draft, issue a HTTP redirect to a page with the success message. This will prevent multiple form submission on page refresh. 
- Nice to have, for logged in user, add "Continue editing" button along with the "Goto Dashboard" button.

**Priority**

- ✅ **High (keeping you from completing day-to-day tasks)**
- Medium (slowing you down)
- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff
- ✅  **Applicants**
- Reviewers
- Partners
- Developers
- General public

**Screenshots**

Screenshot 2023-09-06 at 08 16 20@2x

Related bugs: #3554

### PR DESCRIPTION
**Pull request by theskumar**
Fixes #3556

### CODE REVIEW

**Review by frjo — APPROVED** [review]
Works well for round submissions in my testing.

**Comment by theskumar** [comment]
Merged/rebased with main

**Comment by fourthletter** [comment]
I think this feature is good to go. The only minor issue is the address fields. OTF no longer require these fields.

Screenshot 2023-09-26 1 09 03 PM

**Comment by frjo** [comment]
@fourthletter The address field part is a separate issue.

**Comment by fourthletter** [comment]
OK, thanks!

**Pull request merged**
