### PR TITLE
Make invoice statuses consistent(by {user_role}), update finance 1 to finance, and payment failed status

### LINKED ISSUE #3567: Invoice statuses inconsistency/confusion
- [ ] Update invoice statuses in a way that these should be consistent as 'status' by 'user_roles'. Ex: Approved by Staff, Resubmitted by Applicant.
- [ ] Add invoice status, Payment Failed, that can be changed after paid. 
- [ ] Rename Finance 1 to Finance as it is confusing if Finance 2 settings are not configured. We can keep Finance 2 as it is, just update Finance 1.

### PR DESCRIPTION
**Pull request by sandeepsajan0**
Fixes #3567 

image

Finance1 is the username above not the status. Also, some of the statuses are old that's why there are caps inconsistency, it will not happen with a new invoice.

### CODE REVIEW

**Comment by sandeepsajan0** [comment]
@frjo It is also ready for testing. But I think we might need to rebase it with other PRs to put it on the test. Let me know if it conflicts with any PR.

**Comment by frjo** [comment]
@sandeepsajan0 Yes, some merge conflicts so a rebase would be good, thanks!

**Comment by abhiXII** [comment]
My feedback/observations:

image

1. After the applicant adds the invoice and Staff approves it, there's two statuses 
Approved by Staff (Abhishek Staff) Sept. 21, 2023, 12:44 
Approved an invoice (Abhishek Staff) Sept. 21, 2023, 12:44
we should have only one `Approved by Staff (Abhishek Staff)` this one is fine

2. Vendor name is missing
3. I requested for more info/changes as finance. then edited and resubmitted as staff (as in the image). but the invoice isn't moving back to finance so the finance doesn't see it on their dashboard while the status shows `Resubmitted`
4. Resubmitted one doesn't have the user mentioned like `Approved by staff`. it should say `Resubmitted by staff` or `Resubmitted by vendor`
5. The s of Staff and f of Finance 1 should be small? since they are not names? r in requested also to be small

Is this because this is not on test yet?

**Comment by sandeepsajan0** [comment]
@frjo I accidentally rebased it with the test branch that's why it contains many other changes. However, I think we can put it on test and merge it after other PRs as it contains other test deployed PR changes as well. What do you think or should I create another PR by cherry-picking the commits?

**Comment by frjo** [comment]
@sandeepsajan0 Please create a new PR, got some conflicts trying to merge it in to test.

**Pull request closed without merging**
