### PR TITLE
Custom applicant dashboard header

### PR DESCRIPTION
**Pull request by sandeepsajan0**
Updated the applicant dashboard header as per the latest designs.

Current version(old):
image

Updated version(latest):
image

Used a custom code instead of admin bar component because needed custom implementation that is different from other or common admin bars(headers)

### CODE REVIEW

**Comment by theskumar** [comment]
> Used a custom code instead of admin bar component because needed custom implementation that is different from other or common admin bars(headers)

Can you share some info on it, it see it being fundamentally same. I agree the rest of the admin bar will update as a result of this, but it's that expected here?

**Comment by sandeepsajan0** [comment]
As per the latest designs, almost all the headings are centered except applicant dashboard.
image

image

So, we can keep the admin bar component text-centered, and as it is just one place so can have a custom code like submission and project detail pages.

**Comment by theskumar** [comment]
We should able to pass an extra parameter `align=` to check how we want the headers to be displayed, and can default it to be center at a later sage. I can take a look at structuring the admin-bar a better.

**Comment by frjo** [comment]
@sandeepsajan0 We have merged in everything on test now to main so this can be rebased.

**Review by frjo — APPROVED** [review]

**Pull request merged**
