### PR TITLE
Update activities visibility, hide a few activities for applicant

### LINKED ISSUE #3479: Project team visibility, hide activities from applicant
- [ ] Add a new choice for the Project team and hide that from the submissions comments/communication tab.
- [ ] Hide some activities from applicants/vendors like lead updates.

### PR DESCRIPTION
**Pull request by sandeepsajan0**
Fixes #3479

### CODE REVIEW

**Comment by frjo** [comment]
@sandeepsajan0 A lot of rebasing today :-).

**Comment by sandeepsajan0** [comment]
@frjo Done, rebased it with update status PR.

**Comment by sandeepsajan0** [comment]
@frjo We can hold on to this PR until https://github.com/HyphaApp/hypha/pull/3501 is not merged. I need to fix a few things in this PR on the top of #3501

**Comment by frjo** [comment]
@sandeepsajan0 Test and lint fixes needed.

**Comment by sandeepsajan0** [comment]
@frjo It is ready for testing.

**Comment by abhiXII** [comment]
@sandeepsajan0 I don't think we want to show 
Updated Invoice status to: Approved by Staff
Updated Invoice status to: Changes Requested by Finance 1

We can show approved when it is approved by staff and finance. we can show pending approval till then. we can show changes requested when staff requests changes and sends the invoice back to vendor.

image

**Comment by sandeepsajan0** [comment]
@frjo Its latest version is ready for testing.

**Comment by frjo** [comment]
Deploying latest version to test now.

**Pull request merged**
