### PR TITLE
Rebuild communication and activity feed + assign a comment as task to user

### LINKED ISSUE #3048: Complex comments can break page loading
We had a comment with a very long PGP key that broke page loading. The error said jQuery could not be found. Removing the key from the comment fix the issue directly. But this should not happen in the first place.

It was only via Cloudflare the error showed upp, on local it worked fine. Via Cloudflare the script tag on the bottom of the page was ignored so they loaded too early, before jQuery was loaded.

### LINKED ISSUE #4029: Rebuild comments tab on submissions and projects with htmx and alpinejs
Goals are:

- [ ] Load comments on demand to improve performance of submission and project detail view.
- [ ] Solid implementation of inline editing of comment, current implementation is fragile and a hack.
- [ ] Merged view of comments and activities so the activity feed tab can be removed.

Related #3048

What should we name the new tab to? In vill include both comments and activities.

There is space so maybe just a straight forward "Comments and Activities" or something to that effect?

### PR DESCRIPTION
**Pull request by theskumar**
Fixes #3048 
Fixes #4029

- [x] Introduce machine generated avatars based on the user's name (in-future allow for gravatar or similar service)
- [x] Color Code the user avatar based on their roles 🆕 
- [x] Render the staff roles as label (#3916)
- [x] Reduce the size of the rendered comment box.
- [x]  Merge activities with communication in a single timeline. 🆕 
- [x] Use htmx for comment edit function, the js version seems to break some functionality.
- [x] Use different icons for different activities where possible. 
- [x] Render paginated comment and activities 🆕 
- [x] Cleanup/remove JSON APIs related to comments
- [x] Use the same logic for rendering of comments on the projects module
- [x] ~Async comment add (won't be done in this PR)~
- [x] Deep-link for individual comments
- [x] fix testcases 

## Work in progress screenshots

Screenshot 2024-09-22 at 11  26 34@2x

Screenshot 2024-09-23 at 6  56 56@2x

## Test Steps

 - [ ] Checkout the activity feed and communication

### CODE REVIEW

**Comment by wes-otf** [comment]
@theskumar @frjo I presented this today to the program team and everyone really liked the idea of combining the comments & activities tab - feedback I got was that folks sometimes found it inconvenient to flip back & forth between tabs trying to figure out when different events happened and correlating that to the comments.

**Comment by wes-otf** [comment]
also received some enthusiasm around avatars!

**Comment by theskumar** [comment]
Glad to hear! I'm resuming work on it and keep you posted.

**Comment by theskumar** [comment]
This should too good to review for UX/UI 

Pending items. 
- Update test cases
- make the comment submission async, without page refresh.

**Review by frjo — APPROVED** [review]
Works perfectly in my testing.

**Pull request merged**
